# Generated by Django 5.2.3 on 2025-06-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, unique=True, verbose_name='Từ tiếng Anh')),
                ('vietnamese_translation', models.CharField(max_length=255, verbose_name='Nghĩa tiếng Việt')),
            ],
            options={
                'verbose_name': 'Từ tiếng Anh',
                'verbose_name_plural': 'Các từ tiếng Anh',
            },
        ),
    ]
