# Generated by Django 5.2.3 on 2025-06-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishword',
            options={'verbose_name': 'English Word', 'verbose_name_plural': 'English Words'},
        ),
        migrations.AlterField(
            model_name='englishword',
            name='english_word',
            field=models.CharField(max_length=100, unique=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='vietnamese_translation',
            field=models.CharField(max_length=255, verbose_name='Vietnamese'),
        ),
    ]
