# Generated by Django 5.2.3 on 2025-06-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_englishword_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishword',
            name='vietnamese_translation',
        ),
        migrations.AddField(
            model_name='englishword',
            name='vietnamese_translation_1',
            field=models.CharField(default=1, max_length=255, verbose_name='Vietnamese Meaning 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishword',
            name='vietnamese_translation_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vietnamese Meaning 2'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='vietnamese_translation_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vietnamese Meaning 3'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='vietnamese_translation_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vietnamese Meaning 4'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='vietnamese_translation_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vietnamese Meaning 5'),
        ),
    ]
